# Đồ án 4: Diagonalizable Matrix

**Môn:** Toán ứng dụng và thống kê cho Công nghệ thông tin

**Sinh viên:** Nguyễn Thế Hiển

**MSSV:** 22127107

**Lớp:** 24C05

## 1. Mở đầu

Trong đại số tuyến tính, một ma trận vuông $A$ được gọi là **chéo hóa được** nếu tồn tại ma trận khả nghịch $P$ và ma trận đường chéo $D$ sao cho

$$
A = PDP^{-1}.
$$

Đồ án này tự cài đặt thuật toán chéo hóa theo đúng quy trình lý thuyết trên lớp, đồng thời dùng **Gauss–Jordan** để tính $P^{-1}$. Mục tiêu là hiểu rõ mối liên hệ giữa trị riêng, vector riêng và phép phân rã $PDP^{-1}$, rồi đối chiếu với thư viện và nêu một số ứng dụng.

## 2. Mục tiêu và phạm vi thực hiện

- Cho ma trận $A$ chéo hóa được, tìm $P$, $D$ và $P^{-1}$.
- Không dùng hàm chéo hóa có sẵn của thư viện ở phần tự cài đặt.
- Không dùng hàm tìm nghịch đảo có sẵn; bắt buộc dùng Gauss–Jordan.
- So sánh kết quả với phương thức thư viện tương ứng.
- Trình bày ứng dụng của phép chéo hóa.

## 3. Quy ước ký hiệu

| Ký hiệu | Ý nghĩa |
|---|---|
| $A$ | Ma trận vuông đầu vào (chéo hóa được) |
| $\lambda$ | Trị riêng (eigenvalue) |
| $\mathbf{v}$ | Vector riêng (eigenvector) |
| $P$ | Ma trận các cột là vector riêng |
| $D$ | Ma trận đường chéo chứa các trị riêng |
| $P^{-1}$ | Nghịch đảo của $P$, tính bằng Gauss–Jordan |

## 4. Cấu trúc nội dung

1. Trình bày giải thuật chéo hóa và Gauss–Jordan.
2. Cài đặt các hàm cần thiết.
3. Kiểm tra bằng ví dụ minh họa.
4. So sánh với kết quả từ thư viện.
5. Trình bày ứng dụng, mô tả ý tưởng/hàm và kết luận.


## 5. Giải thuật chéo hóa


Cho $A$ là ma trận vuông cấp $n$ **chéo hóa được**. Mục tiêu là tìm $P$, $D$, $P^{-1}$ sao cho


$$
A = PDP^{-1}.
$$


Quy trình dưới đây bám theo lý thuyết và bài tập trên lớp.


### Bước 1. Lập và giải phương trình đặc trưng


Xét đa thức đặc trưng


$$
p(\lambda)=\det(A-\lambda I)=0
\quad\text{(tương đương }\det(\lambda I-A)=0\text{)}.
$$


Các nghiệm $\lambda_1,\lambda_2,\dots,\lambda_n$ là trị riêng của $A$.


**Ví dụ cách làm trên lớp với ma trận $2\times 2$:**


$$
A=\begin{bmatrix}a&b\\c&d\end{bmatrix}
\Rightarrow
A-\lambda I=\begin{bmatrix}a-\lambda&b\\c&d-\lambda\end{bmatrix}
\Rightarrow
p(\lambda)=(a-\lambda)(d-\lambda)-bc.
$$


Giải $p(\lambda)=0$ để được các trị riêng.


**Trong chương trình:** để tổng quát cho cấp $n$, hệ số của $\det(\lambda I-A)$ được tính bằng Faddeev–LeVerrier, rồi dùng `numpy.roots` chỉ để giải nghiệm đa thức. **Không** dùng hàm chéo hóa có sẵn (`numpy.linalg.eig`, ...).


### Bước 2. Tìm không gian riêng


Với mỗi trị riêng $\lambda_i$, giải hệ thuần nhất


$$
(A-\lambda_i I)\mathbf{x}=\mathbf{0}.
$$


Các nghiệm khác $\mathbf{0}$ tạo thành không gian riêng $E_{\lambda_i}$. Cách làm:


1. Lập ma trận $A-\lambda_i I$.
2. Đưa về dạng bậc thang rút gọn (RREF) bằng Gauss–Jordan.
3. Xác định biến tự do; mỗi biến tự do cho một vector riêng cơ sở.


### Bước 3. Dựng ma trận $P$ và $D$


- Ghép $n$ vector riêng độc lập tuyến tính thành các cột của $P$:


$$
P=[\mathbf{v}_1\mid\mathbf{v}_2\mid\dots\mid\mathbf{v}_n].
$$


- Đặt


$$
D=\operatorname{diag}(\lambda_1,\lambda_2,\dots,\lambda_n)
$$


theo đúng thứ tự tương ứng với các cột của $P$.


Khi đó $AP=PD$, suy ra $A=PDP^{-1}$.


### Bước 4. Tìm $P^{-1}$ bằng Gauss–Jordan


**Không dùng** hàm nghịch đảo có sẵn. Lập ma trận mở rộng và biến đổi hàng:


$$
[P\mid I]
\xrightarrow{\text{Gauss–Jordan}}
[I\mid P^{-1}].
$$


Các phép biến đổi hàng được dùng:


1. Đổi chỗ hai hàng (chọn pivot khác 0).
2. Nhân một hàng với số khác 0 (đưa pivot về 1).
3. Cộng một bội của hàng này vào hàng khác (khử cột pivot).


Nếu không tìm được đủ pivot thì $P$ không khả nghịch.


### Điều kiện chéo hóa được


$A$ chéo hóa được khi và chỉ khi tồn tại đủ $n$ vector riêng độc lập tuyến tính, tức tổng số chiều các không gian riêng bằng $n$. Nếu thiếu, chương trình sẽ báo lỗi.


### Kiểm tra tính đúng đắn


Sau khi có $P$, $D$, $P^{-1}$, kiểm tra:


$$
A\approx PDP^{-1},\qquad PP^{-1}\approx I,\qquad AP\approx PD.
$$



In [13]:
import numpy as np

np.set_printoptions(precision=4, suppress=True)
TOL = 1e-10

## 6. Cài đặt thuật toán


Phần này gồm các hàm:


- `rref`: đưa ma trận về dạng bậc thang rút gọn bằng Gauss–Jordan.
- `gauss_jordan_inverse`: tìm nghịch đảo từ $[P \mid I]$.
- `char_poly_coeffs`: tính hệ số đa thức đặc trưng bằng Faddeev–LeVerrier.
- `eigenvalues_from_charpoly`: tìm trị riêng từ đa thức đặc trưng.
- `nullspace`: tìm cơ sở không gian nghiệm của $M\mathbf{x}=\mathbf{0}$.
- `diagonalize`: ghép các bước trên để trả về $P$ và $D$.


In [14]:
def rref(M, tol=TOL):
    """Đưa ma trận về dạng bậc thang rút gọn (RREF) bằng Gauss-Jordan."""
    A = np.array(M, dtype=float).copy()
    m, n = A.shape
    row = 0
    pivots = []

    for col in range(n):
        pivot = None
        for i in range(row, m):
            if abs(A[i, col]) > tol:
                pivot = i
                break
        if pivot is None:
            continue

        if pivot != row:
            A[[row, pivot]] = A[[pivot, row]]

        A[row] = A[row] / A[row, col]

        for i in range(m):
            if i != row and abs(A[i, col]) > tol:
                A[i] = A[i] - A[i, col] * A[row]

        pivots.append(col)
        row += 1
        if row == m:
            break

    A[np.abs(A) < tol] = 0.0
    return A, pivots


def gauss_jordan_inverse(P, tol=TOL):
    """Tìm P^{-1} bằng Gauss-Jordan trên ma trận mở rộng [P | I]."""
    P = np.array(P, dtype=float)
    if P.ndim != 2 or P.shape[0] != P.shape[1]:
        raise ValueError('Ma trận phải vuông để tìm nghịch đảo.')

    n = P.shape[0]
    aug = np.hstack([P, np.eye(n)])
    R, pivots = rref(aug, tol=tol)

    if len(pivots) < n or any(p >= n for p in pivots):
        raise ValueError('Ma trận không khả nghịch.')

    left = R[:, :n]
    if not np.allclose(left, np.eye(n), atol=1e-6):
        raise ValueError('Gauss-Jordan không đưa về I; ma trận có thể suy biến.')

    return R[:, n:]


def matrix_rank(M, tol=TOL):
    """Hạng ma trận = số cột pivot sau khi RREF."""
    _, pivots = rref(M, tol=tol)
    return len(pivots)


def char_poly_coeffs(A):
    """Hệ số của det(λI - A) theo Faddeev-LeVerrier (bậc cao -> thấp)."""
    A = np.array(A, dtype=float)
    n = A.shape[0]
    coeffs = [1.0]
    B = np.eye(n)

    for k in range(1, n + 1):
        M = A @ B
        ck = -np.trace(M) / k
        coeffs.append(ck)
        B = M + ck * np.eye(n)

    return np.array(coeffs, dtype=float)


def eigenvalues_from_charpoly(A):
    """Tìm trị riêng bằng cách giải đa thức đặc trưng."""
    coeffs = char_poly_coeffs(A)
    roots = np.roots(coeffs)

    vals = []
    for r in roots:
        if abs(r.imag) < 1e-8:
            v = float(r.real)
            if abs(v - round(v)) < 1e-8:
                v = float(round(v))
            vals.append(v)
        else:
            vals.append(complex(r))

    vals = sorted(vals, key=lambda x: (x.real, x.imag) if isinstance(x, complex) else (x, 0.0))
    return vals


def nullspace(M, tol=1e-8):
    """Tìm một cơ sở của không gian nghiệm M x = 0 từ RREF."""
    M = np.array(M, dtype=float)
    _, n = M.shape
    R, pivots = rref(M, tol=tol)
    free_vars = [j for j in range(n) if j not in pivots]

    basis = []
    for f in free_vars:
        x = np.zeros(n, dtype=float)
        x[f] = 1.0
        for i, p in enumerate(pivots):
            x[p] = -R[i, f]

        scale = np.max(np.abs(x))
        if scale > tol:
            x = x / scale
        x[np.abs(x) < tol] = 0.0
        basis.append(x)

    return basis


def diagonalize(A, tol=1e-8):
    """Chéo hóa A = P D P^{-1}. Trả về P và D (không dùng hàm eig có sẵn)."""
    A = np.array(A, dtype=float)
    if A.ndim != 2 or A.shape[0] != A.shape[1]:
        raise ValueError('A phải là ma trận vuông.')

    n = A.shape[0]
    eigs = eigenvalues_from_charpoly(A)

    cols = []
    used_lams = []

    for lam in eigs:
        if isinstance(lam, complex):
            raise ValueError('Gặp trị riêng phức; đồ án minh họa trên ma trận thực chéo hóa được.')

        vecs = nullspace(A - lam * np.eye(n), tol=tol)
        for v in vecs:
            trial = np.column_stack(cols + [v]) if cols else v.reshape(-1, 1)
            if matrix_rank(trial, tol=tol) > len(cols):
                cols.append(v)
                used_lams.append(lam)
            if len(cols) == n:
                break
        if len(cols) == n:
            break

    if len(cols) < n:
        raise ValueError('Không đủ eigenvector độc lập; A có thể không chéo hóa được.')

    P = np.column_stack(cols)
    D = np.diag(used_lams)
    return P, D


def reconstruct(P, D, P_inv):
    """Tái tạo A từ P, D, P^{-1}."""
    return P @ D @ P_inv

## 7. Ví dụ minh họa


Ta xét một ma trận $2\times 2$ chéo hóa được đơn giản để kiểm tra từng bước.


In [15]:
A = np.array([
    [2, 1],
    [0, 3],
], dtype=float)

print('A =')
print(A)
print('\nHệ số đa thức đặc trưng det(λI - A):', char_poly_coeffs(A))
print('Trị riêng tìm được:', eigenvalues_from_charpoly(A))

P, D = diagonalize(A)
P_inv = gauss_jordan_inverse(P)
A_hat = reconstruct(P, D, P_inv)

print('\nP =')
print(P)
print('\nD =')
print(D)
print('\nP^{-1} =')
print(P_inv)
print('\nP D P^{-1} =')
print(A_hat)
print('\nA gần bằng P D P^{-1}:', np.allclose(A, A_hat))
print('Sai số ||A - PDP^{-1}|| =', np.linalg.norm(A - A_hat))

A =
[[2. 1.]
 [0. 3.]]

Hệ số đa thức đặc trưng det(λI - A): [ 1. -5.  6.]
Trị riêng tìm được: [2.0, 3.0]

P =
[[1. 1.]
 [0. 1.]]

D =
[[2. 0.]
 [0. 3.]]

P^{-1} =
[[ 1. -1.]
 [ 0.  1.]]

P D P^{-1} =
[[2. 1.]
 [0. 3.]]

A gần bằng P D P^{-1}: True
Sai số ||A - PDP^{-1}|| = 0.0


## 8. Ví dụ bổ sung


Ví dụ thứ hai dùng ma trận $3\times 3$ có ba trị riêng phân biệt. Ví dụ này giúp kiểm tra thuật toán khi số chiều tăng và khi cần ghép nhiều vector riêng.


In [16]:
A2 = np.array([
    [4, -2, 1],
    [2,  0, 1],
    [-1, 2, 2],
], dtype=float)

P2, D2 = diagonalize(A2)
P2_inv = gauss_jordan_inverse(P2)
A2_hat = reconstruct(P2, D2, P2_inv)

print('A2 =')
print(A2)
print('\nTrị riêng:', eigenvalues_from_charpoly(A2))
print('\nP2 =')
print(P2)
print('\nD2 =')
print(D2)
print('\nP2^{-1} =')
print(P2_inv)
print('\nP2 D2 P2^{-1} =')
print(A2_hat)
print('\nA2 gần bằng P2 D2 P2^{-1}:', np.allclose(A2, A2_hat))
print('Sai số ||A2 - P2 D2 P2^{-1}|| =', np.linalg.norm(A2 - A2_hat))

A2 =
[[ 4. -2.  1.]
 [ 2.  0.  1.]
 [-1.  2.  2.]]

Trị riêng: [1.0, 2.0, 3.0]

P2 =
[[-1.  -1.   1. ]
 [-1.  -0.5  1. ]
 [ 1.   1.   1. ]]

D2 =
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]

P2^{-1} =
[[ 1.5 -2.   0.5]
 [-2.   2.   0. ]
 [ 0.5  0.   0.5]]

P2 D2 P2^{-1} =
[[ 4. -2.  1.]
 [ 2.  0.  1.]
 [-1.  2.  2.]]

A2 gần bằng P2 D2 P2^{-1}: True
Sai số ||A2 - P2 D2 P2^{-1}|| = 1.2947314098277875e-15


### Nhận xét ví dụ


Ở cả hai ví dụ, kết quả `A gần bằng P D P^{-1}` đều là `True`. Điều đó cho thấy:


- Các trị riêng và vector riêng đã được xác định đúng hướng.
- Ma trận $P$ khả nghịch và Gauss–Jordan tìm được $P^{-1}$ hợp lệ.
- Thứ tự trị riêng trên đường chéo của $D$ khớp với thứ tự cột của $P$.


## 9. So sánh với thư viện


Để đối chiếu, ta dùng `numpy.linalg.eig`. Lưu ý quan trọng:


- Các cột của $P$ có thể **khác dấu** hoặc **khác chuẩn hóa** so với thư viện.
- Thứ tự trị riêng trên $D$ có thể khác.
- Tiêu chí so sánh hợp lý là kiểm tra $A \approx PDP^{-1}$ ở cả hai cách, chứ không yêu cầu từng phần tử của $P$ trùng khớp tuyệt đối.


Phần này chỉ dùng để đối chiếu, **không thay thế** thuật toán tự cài ở trên.


In [17]:
def compare_with_numpy(A, P, D, P_inv):
    A = np.array(A, dtype=float)
    vals_lib, vecs_lib = np.linalg.eig(A)

    # NumPy trả về trị riêng/vector riêng dạng phức nói chung; lấy phần thực nếu ảo rất nhỏ
    vals_lib = np.real_if_close(vals_lib, tol=1e8)
    vecs_lib = np.real_if_close(vecs_lib, tol=1e8)

    D_lib = np.diag(vals_lib)
    # Ở phần mở rộng được phép dùng nghịch đảo thư viện để dựng lại A
    P_lib_inv = np.linalg.inv(vecs_lib)
    A_from_lib = vecs_lib @ D_lib @ P_lib_inv
    A_from_manual = P @ D @ P_inv

    print('Trị riêng (tự cài):', np.diag(D))
    print('Trị riêng (numpy): ', vals_lib)
    print('\nP tự cài =')
    print(P)
    print('\nP từ numpy.linalg.eig =')
    print(vecs_lib)
    print('\n||A - P D P^{-1}|| (tự cài) =', np.linalg.norm(A - A_from_manual))
    print('||A - V Λ V^{-1}|| (numpy) =', np.linalg.norm(A - A_from_lib))
    print('Hai cách đều tái tạo được A:',
          np.allclose(A, A_from_manual) and np.allclose(A, A_from_lib))


print('=== So sánh trên ma trận A ===')
compare_with_numpy(A, P, D, P_inv)
print('\n=== So sánh trên ma trận A2 ===')
compare_with_numpy(A2, P2, D2, P2_inv)

=== So sánh trên ma trận A ===
Trị riêng (tự cài): [2. 3.]
Trị riêng (numpy):  [2. 3.]

P tự cài =
[[1. 1.]
 [0. 1.]]

P từ numpy.linalg.eig =
[[1.     0.7071]
 [0.     0.7071]]

||A - P D P^{-1}|| (tự cài) = 0.0
||A - V Λ V^{-1}|| (numpy) = 1.1102230246251565e-16
Hai cách đều tái tạo được A: True

=== So sánh trên ma trận A2 ===
Trị riêng (tự cài): [1. 2. 3.]
Trị riêng (numpy):  [1. 2. 3.]

P tự cài =
[[-1.  -1.   1. ]
 [-1.  -0.5  1. ]
 [ 1.   1.   1. ]]

P từ numpy.linalg.eig =
[[ 0.5774  0.6667  0.5774]
 [ 0.5774  0.3333  0.5774]
 [-0.5774 -0.6667  0.5774]]

||A - P D P^{-1}|| (tự cài) = 1.2947314098277875e-15
||A - V Λ V^{-1}|| (numpy) = 3.531835650735641e-15
Hai cách đều tái tạo được A: True


## 10. Ứng dụng của chéo hóa


Phép chéo hóa $A = PDP^{-1}$ rất hữu ích vì nhiều phép tính trên $A$ có thể chuyển về tính trên ma trận đường chéo $D$, vốn đơn giản hơn rất nhiều.


### 10.1. Tính lũy thừa ma trận


Nếu $A = PDP^{-1}$ thì


$$
A^k = PD^k P^{-1}.
$$


Vì $D$ là ma trận đường chéo, $D^k$ chỉ cần lũy thừa từng phần tử trên đường chéo. Đây là cách hiệu quả để tính $A^k$ khi $k$ lớn, hoặc giải hệ động học rời rạc $\mathbf{x}_{k+1} = A\mathbf{x}_k$.


### 10.2. Giải hệ phương trình vi phân tuyến tính


Với hệ $\mathbf{x}' = A\mathbf{x}$, nếu $A$ chéo hóa được thì nghiệm có dạng tổ hợp các hàm mũ $e^{\lambda_i t}$ theo các hướng vector riêng. Chéo hóa giúp tách hệ liên kết thành các phương trình độc lập trên cơ sở riêng.


### 10.3. Chuỗi Markov và ổn định dài hạn


Trong mô hình Markov, ma trận chuyển trạng thái thường được phân tích qua phổ (trị riêng). Trị riêng lớn nhất và không gian riêng tương ứng giúp hiểu hành vi hội tụ của hệ khi thời gian đủ lớn.


### 10.4. Liên hệ với học máy / giảm chiều


Nhiều kỹ thuật như PCA dựa trên phân tích phổ của ma trận hiệp phương sai. Dù PCA thường dùng trị riêng của ma trận đối xứng (có thể trực giao hóa), ý tưởng nền vẫn là biểu diễn dữ liệu theo các hướng riêng quan trọng.


### Minh họa nhanh: tính $A^5$ nhờ chéo hóa


In [18]:
# Minh họa A^k = P D^k P^{-1}
k = 5
Dk = np.diag(np.diag(D) ** k)
A_power_via_diag = P @ Dk @ P_inv
A_power_direct = np.linalg.matrix_power(A, k)

print(f'A^{k} tính qua chéo hóa =')
print(A_power_via_diag)
print(f'\nA^{k} tính trực tiếp =')
print(A_power_direct)
print('\nHai kết quả gần bằng nhau:', np.allclose(A_power_via_diag, A_power_direct))

A^5 tính qua chéo hóa =
[[ 32. 211.]
 [  0. 243.]]

A^5 tính trực tiếp =
[[ 32. 211.]
 [  0. 243.]]

Hai kết quả gần bằng nhau: True


## 11. Mô tả ý tưởng thực hiện


Ý tưởng chính của đồ án là **bám sát quy trình lý thuyết trên lớp**, không gọi thẳng hàm chéo hóa hay hàm nghịch đảo có sẵn ở phần chính.


### Luồng thực hiện


1. **Lập đa thức đặc trưng:** dùng Faddeev–LeVerrier để lấy các hệ số $c_k$ của $\det(\lambda I-A)$.
2. **Tìm trị riêng:** giải $p(\lambda)=0$ bằng `numpy.roots` (chỉ giải nghiệm đa thức).
3. **Tìm vector riêng:** với mỗi $\lambda$, đưa $A-\lambda I$ về RREF bằng Gauss–Jordan, đọc biến tự do để dựng cơ sở $E_\lambda$.
4. **Dựng $P$ và $D$:** ghép các vector riêng độc lập thành cột của $P$; đặt các $\lambda$ tương ứng lên đường chéo của $D$.
5. **Tìm $P^{-1}$:** Gauss–Jordan trên $[P\mid I]$ đến khi thu được $[I\mid P^{-1}]$.
6. **Kiểm chứng:** tính lại $PDP^{-1}$ và đối chiếu với `numpy.linalg.eig` ở phần mở rộng.


### Một số quyết định kỹ thuật


- Dùng chung hàm `rref` cho cả tìm nullspace và tìm nghịch đảo, để thống nhất thuật toán Gauss–Jordan.
- So sánh số học dùng ngưỡng `tol` / `np.allclose` vì có sai số dấu chấm động.
- Vector riêng không duy nhất (khác dấu/tỷ lệ), nên tiêu chí đúng là $A\approx PDP^{-1}$, không phải từng phần tử của $P$ trùng với thư viện.
- Phần mở rộng mới được phép dùng `numpy.linalg.eig` và `numpy.linalg.inv` để so sánh.


## 12. Mô tả các hàm


| Hàm | Input | Output / Vai trò |
|---|---|---|
| `rref(M)` | Ma trận $M$ | Ma trận RREF và danh sách cột pivot; cài Gauss–Jordan. |
| `gauss_jordan_inverse(P)` | Ma trận vuông $P$ | $P^{-1}$ tìm từ $[P\mid I]$; **không** dùng `np.linalg.inv`. |
| `matrix_rank(M)` | Ma trận $M$ | Hạng = số pivot sau RREF; dùng kiểm tra độc lập tuyến tính. |
| `char_poly_coeffs(A)` | Ma trận vuông $A$ | Hệ số của $\det(\lambda I-A)$ (bậc cao → thấp). |
| `eigenvalues_from_charpoly(A)` | Ma trận vuông $A$ | Danh sách trị riêng từ việc giải đa thức đặc trưng. |
| `nullspace(M)` | Ma trận $M$ | Một cơ sở của $\{\mathbf{x}: M\mathbf{x}=\mathbf{0}\}$. |
| `diagonalize(A)` | Ma trận vuông $A$ chéo hóa được | Cặp $(P,D)$ sao cho $A=PDP^{-1}$; **không** dùng `eig`. |
| `reconstruct(P,D,P_inv)` | $P$, $D$, $P^{-1}$ | Tích $PDP^{-1}$ để kiểm tra. |
| `compare_with_numpy(...)` | $A$ và kết quả tự cài | Đối chiếu với `numpy.linalg.eig` (phần mở rộng). |


### Quan hệ giữa các hàm


$$
A
\xrightarrow{\texttt{char\_poly\_coeffs}/\texttt{eigenvalues\_from\_charpoly}}
\{\lambda_i\}
\xrightarrow{\texttt{nullspace}}
\{\mathbf{v}_i\}
\xrightarrow{\texttt{diagonalize}}
(P,D)
\xrightarrow{\texttt{gauss\_jordan\_inverse}}
P^{-1}.
$$


## 13. Kết luận


Đồ án đã hoàn thành các yêu cầu:


- Đầu bài có thông tin sinh viên và trình bày giải thuật chéo hóa.
- Phần chính tự cài chéo hóa để tìm $P$, $D$ và dùng Gauss–Jordan để tìm $P^{-1}$.
- Phần mở rộng so sánh với thư viện và trình bày ứng dụng.
- Cuối bài có mô tả ý tưởng thực hiện và mô tả các hàm.


Các ví dụ kiểm tra cho thấy $A\approx PDP^{-1}$, đồng thời sai số tái tạo rất nhỏ và tương đương kết quả NumPy.


## 14. Tài liệu tham khảo


- Giáo trình / bài giảng Toán ứng dụng và Thống kê trong CNTT (HCMUS).
- Nội dung lý thuyết chéo hóa ma trận và thuật toán Gauss–Jordan trên lớp.
- Tài liệu NumPy: `numpy.linalg.eig`, `numpy.roots`.
- Thuật toán Faddeev–LeVerrier để tính đa thức đặc trưng.

